# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-10 13:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('GRT', '인사말'), ('BSN', '사업안내'), ('ORG', '조직안내'), ('MAP', '오시는길'), ('USE', '이용안내')], max_length=3)),
                ('title', models.CharField(max_length=45)),
                ('contents', models.TextField()),
                ('image', models.ImageField(blank=True, upload_to='info/%Y')),
                ('modified_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'other_board',
                'verbose_name': 'info',
                'ordering': ('-modified_date',),
            },
        ),
    ]
