# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-08 07:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0002_auto_20161208_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='category',
            field=models.CharField(choices=[('OLD_GRT', '전 원장 인사말'), ('GRT', '현 원장 인사말'), ('BSN', '사업안내'), ('ORG', '조직안내'), ('MAP', '오시는길'), ('USE', '이용안내')], max_length=7),
        ),
    ]
