# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-21 08:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0003_auto_20161208_1627'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='info',
            options={'ordering': ('-modified_date',), 'verbose_name': '\uae30\uad00\uc18c\uac1c\uae00', 'verbose_name_plural': '\uae30\uad00\uc18c\uac1c\uae00'},
        ),
    ]
