# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-15 07:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='avatar',
        ),
        migrations.RemoveField(
            model_name='user',
            name='nickname',
        ),
        migrations.AddField(
            model_name='user',
            name='birth',
            field=models.DateField(null=True, verbose_name='생일'),
        ),
        migrations.AddField(
            model_name='user',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='가입일'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='login_id',
            field=models.CharField(default='harvey', max_length=11, unique=True, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(default='harvey', max_length=10, verbose_name='이름'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='open_email',
            field=models.BooleanField(default=False, verbose_name='이메일 공개여부'),
        ),
        migrations.AddField(
            model_name='user',
            name='open_login_id',
            field=models.BooleanField(default=False, verbose_name='핸드폰 번호 공개여부'),
        ),
        migrations.AddField(
            model_name='user',
            name='open_picture',
            field=models.BooleanField(default=False, verbose_name='프로필 사진 공개여부'),
        ),
        migrations.AddField(
            model_name='user',
            name='open_work',
            field=models.BooleanField(default=False, verbose_name='직장 공개여부'),
        ),
        migrations.AddField(
            model_name='user',
            name='open_work_phone',
            field=models.BooleanField(default=False, verbose_name='직장 전화 공개여부'),
        ),
        migrations.AddField(
            model_name='user',
            name='open_work_position',
            field=models.BooleanField(default=False, verbose_name='직장 직위 공개여부'),
        ),
        migrations.AddField(
            model_name='user',
            name='period',
            field=models.IntegerField(default=11, verbose_name='기수'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='picture',
            field=models.ImageField(blank=True, upload_to='', verbose_name='프로필 사진'),
        ),
        migrations.AddField(
            model_name='user',
            name='position',
            field=models.CharField(default='일반회원', max_length=15, verbose_name='동문회 직책'),
        ),
        migrations.AddField(
            model_name='user',
            name='position_all',
            field=models.CharField(blank=True, max_length=15, verbose_name='총 동문회 직책'),
        ),
        migrations.AddField(
            model_name='user',
            name='work',
            field=models.CharField(blank=True, max_length=45, verbose_name='직장'),
        ),
        migrations.AddField(
            model_name='user',
            name='work_phone',
            field=models.CharField(blank=True, max_length=14, verbose_name='직장 전화'),
        ),
        migrations.AddField(
            model_name='user',
            name='work_position',
            field=models.CharField(blank=True, max_length=45, verbose_name='직장 직위'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=255, unique=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='사용여부'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_admin',
            field=models.BooleanField(default=False, verbose_name='관리자'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_login',
            field=models.DateTimeField(auto_now=True, verbose_name='마지막 로그인'),
        ),
    ]
