# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-08 13:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='position',
            field=models.CharField(default='일반회원', max_length=15),
        ),
        migrations.AlterField(
            model_name='user',
            name='position_all',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
