# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-15 07:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0002_auto_20161115_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='period',
            field=models.IntegerField(blank=True, verbose_name='기수'),
        ),
    ]
