# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-09 16:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0002_auto_20161108_2237'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ('-period',), 'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
    ]
