# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-17 14:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0003_auto_20161115_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='period',
            field=models.IntegerField(blank=True, default=0, verbose_name='기수'),
        ),
    ]
