# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-14 04:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0005_user_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='login_id',
            field=models.CharField(max_length=11, unique=True),
        ),
    ]
