# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-21 08:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0006_user_is_first_login'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': '\uc0ac\uc6a9\uc790', 'verbose_name_plural': '\uc0ac\uc6a9\uc790'},
        ),
    ]
