# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-17 09:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='FreeBoard/%Y/%m/%d'),
        ),
    ]
