# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-08 22:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0005_auto_20161209_0651'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='writer',
        ),
    ]
