# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-08 22:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0007_post_writer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='author',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
