# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-08 23:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0009_auto_20161209_0819'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='writer',
            new_name='writer_id',
        ),
    ]
