# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-07 19:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0003_auto_20161206_1631'),
        ('notice', '0003_auto_20161208_0358'),
    ]

    operations = [
    ]
