# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-08 22:29
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notice', '0008_auto_20161209_0718'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='author',
            new_name='nt_author',
        ),
        migrations.RemoveField(
            model_name='post',
            name='writer',
        ),
        migrations.AddField(
            model_name='post',
            name='nt_writer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
