# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-08 22:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0009_auto_20161209_0729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='nt_writer',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
