# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-21 08:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0011_auto_20161223_0232'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': '\ub313\uae00', 'verbose_name_plural': '\ub313\uae00'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': '\uac8c\uc2dc\uae00', 'verbose_name_plural': '\uac8c\uc2dc\uae00'},
        ),
    ]
